version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  # Только HTTP

    environment:
      - ENV=development
      - DATABASE_URL=postgresql://user:pass@db:5432/drakon
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: drakon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  redis_data:
  postgres_data: